# Generated by Django 5.2.9 on 2025-12-20 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0002_comment_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('STATUS_CHANGED', 'Status Changed'), ('COMMENT_ADDED', 'Comment Added'), ('TASK_ASSIGNED', 'Task Assigned'), ('PROJECT_CREATED', 'Project Created'), ('USER_MENTIONED', 'User Mentioned')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_activities', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to='projects.comment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to='projects.task')),
            ],
            options={
                'db_table': 'feeds',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='feeds_created_de02b2_idx'), models.Index(fields=['organization', '-created_at'], name='feeds_organiz_d2a4e1_idx'), models.Index(fields=['actor', '-created_at'], name='feeds_actor_i_29ae7a_idx')],
            },
        ),
    ]
